app/main/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField, SubmitField, validators
from flask_wtf.file import FileField, FileAllowed, FileRequired
from .. import photos, audio

class AlbumForm(Form):
    title = StringField("Album title")
    artist = StringField("Artist's name")
    genre = StringField("Genre")
    logo = FileField("Upload a logo for your album", validators=[FileRequired(), FileAllowed(photos, 'Can only upload photos!')])
    submit = SubmitField('Submit')


class SongForm(Form):
    title = StringField("Enter song title")
    audio = FileField("Upload song", validators=[FileRequired(), FileAllowed(audio, 'Can only upload photos!')])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, flash, redirect, url_for, jsonify, request, send_from_directory, current_app, abort
from . import main
from .. import db, photos, audio
from .forms import AlbumForm, SongForm
from ..models import Album, Song, User
from .. import db
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
import os

@main.route("/", methods=['GET', 'POST'])
@main.route("/home",methods=['GET', 'POST'])
@main.route("/index/<int:page>", methods=['GET', 'POST'])
def index(page=1):
    if not current_user.is_authenticated:
        return render_template("auth/index.html")
    albums = Album.query.filter_by(user=current_user).paginate(page, current_app.config['ALBUMS_PER_PAGE'], False)
    return render_template("main/index.html", albums=albums)


@main.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    query = request.form.get('q')
    if query:
        albums = Album.query.whoosh_search(query).all()
        songs = Song.query.whoosh_search(query).all()
        return render_template('main/index.html', albums=albums, songs=songs)
    return redirect(url_for('main.index'))


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ))


@main.route("/albums/add", methods=['GET', 'POST'])
def add_album():
    if not current_user.is_authenticated:
        flash('login/register to add albums')
        return redirect(url_for('auth.login'))
    form = AlbumForm()
    if form.validate_on_submit():
        filename = photos.save(request.files['logo'])
        url = photos.url(filename)
        artist = form.artist.data
        album_title = form.title.data
        genre = form.genre.data
        album = Album(artist=artist, album_title=album_title, genre=genre,album_logo=filename,logo_url=url, user=current_user)
        db.session.add(album)
        db.session.commit()
        flash("Album {} added".format(album_title))
        return redirect(url_for('main.index'))
    else:
        flash_errors(form)
    return render_template('main/add_album.html', form=form)


@main.route("/albums/delete/<int:album_id>", methods=['DELETE', 'POST'])
@login_required
def delete_album(album_id):
    album = Album.query.filter_by(id=album_id).first_or_404()
    db.session.delete(album)
    db.session.commit()
    return redirect(url_for('main.index'))


@main.route("/songs/create/<int:album_id>", methods=['POST', 'GET'])
def add_song(album_id):
    if not current_user.is_authenticated:
        flash('login/register to add songs')
        return redirect(url_for('auth.login'))
    form = SongForm()
    albums = Album.query.filter_by(user=current_user).all()
    album = filter(lambda alb: alb.id==album_id, albums)
    album = album[0]
    if form.validate_on_submit():
        song_filename = audio.save(request.files['audio'])
        song_url = audio.url(song_filename)
        song_title = form.title.data
        song = Song(song_title=song_title,audio_url=song_url, audio_file=song_filename,album_id=album.id)
        db.session.add(song)
        db.session.commit()
        flash("[song] {} added".format(song_title))
        return redirect(url_for('main.detail',album_id=album.id))
    else:
        flash_errors(form)
    return render_template('main/add_song.html', form=form, album=album)


@main.route("/albums/detail/<int:album_id>")
def detail(album_id):
    if not current_user.is_authenticated:
        flash('login/register to view your albums')
        return redirect(url_for('auth.login'))
    albums = Album.query.filter_by(user=current_user).all()
    album = filter(lambda alb: alb.id==album_id, albums)
    album = album[0]
    songs = Song.query.filter_by(album_id=album.id).all()
    return render_template('main/details.html', album=album, songs=songs)


@main.route("/albums/favorite/<int:album_id>", methods=['POST', 'GET'])
@login_required
def favorite_album(album_id):
    album = Album.query.filter_by(id=album_id).first()
    if album.is_favorite:
        album.is_favorite = False
    else:
        album.is_favorite = True
    db.session.add(album)
    db.session.commit()
    resp = jsonify({'success': True})
    resp.status_code = 200
    return resp


@main.route('/photos/<filename>')
def uploaded_image(filename):
    return send_from_directory(os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'photos'), filename)


@main.route('/audio/<filename>')
def uploaded_song(filename):
    return send_from_directory(os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'audio'), filename)



@main.route("/songs/delete/<int:album_id>/<int:song_id>", methods=['POST', 'GET'])
@login_required
def delete_song(album_id, song_id):
    albums = Album.query.filter_by(user=current_user).all()
    album = filter(lambda alb: alb.id == album_id, albums)
    album = album[0]
    songs = Song.query.filter_by(album_id=album.id).all()
    song = filter(lambda song: song.id==song_id, songs)
    if len(song)>0:
        db.session.delete(song[0])
        db.session.commit()
        flash("Deleted ".format(song[0].song_title))
        return redirect(url_for('main.detail', album_id=album.id))
    abort(404)


@main.route("/songs/favorite/<int:song_id>")
@login_required
def favorite_song(song_id):
    song = Song.query.filter_by(id=song_id).first()
    if song.is_favorite:
        song.is_favorite = False
    else:
        song.is_favorite = True
    db.session.add(song)
    db.session.commit()
    resp = jsonify({'success': True})
    resp.status_code = 200
    return resp

@main.route("/songs/<song_filter>", methods=['GET', 'POST'])
@login_required
def songs(song_filter):
    user_albums = Album.query.filter_by(user=current_user).all()
    song_ids = []
    for album in user_albums:
        for song in Song.query.filter_by(album=album).all():
            song_ids.append(song.id)
    user_songs = [Song.query.filter_by(id=id).first() for id in song_ids]
    if song_filter== 'favorites':
        user_songs = filter(lambda song: song.is_favorite == True, user_songs)
    return render_template('main/songs.html', song_list=user_songs,song_filter=song_filter)

app/templates/main/405.html
{% extends "error.html" %}
{% block title %}playsloth - 405{% endblock %}
{% block page_content %}
<div class="container">
    <h3>Oops! We can't allow you past here ;-)</h3>
     <a href="{{ url_for('main.index') }}"><button type="button" class="btn btn-primary">Take me home!</button></a>
</div>
{% endblock %}

app/templates/main/_helpers.html
 {% macro paginate(paginator, endpoint) %}
        {# A generally pluggable pagination macro, just supply it with the pagination object #}
        {# formatted for Bootstrap 3 #}
    <nav aria-label="Page navigation" class="text-center">
      <ul class="pagination">
        <li {% if not paginator.has_prev %}class="disabled"{% endif %}>
          <a href="{% if paginator.has_prev %}{{ url_for(endpoint, page=paginator.page - 1, **kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% for page in paginator.iter_pages() %}
          {% if page %}
            <li {% if page == paginator.page %} class="active"{% endif %}><a href="{{ url_for( endpoint, page=page, **kwargs) }}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="#">&hellip;</a></li>
          {% endif %}
          {% endfor %}
        <li {% if not paginator.has_next %}class="disabled"{% endif %}>
          <a href="{% if paginator.has_next %}{{ url_for(endpoint, page=paginator.page + 1, **kwargs) }}{% else %}#{% endif %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
 {% endmacro %}

app/templates/main/add_album.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    {{ wtf.quick_form(form) }}

                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is playsloth?</h3>
                    <p>playsloth is an app that allows you to upload and store all of your music on the cloud.</p>
                    <h3>How do I add music?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

app/templates/main/add_song.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}
{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{{ url_for('main.detail', album_id=album.id) }}">
                            {% if album.album_logo %}
                                <img src="{{ url_for('main.uploaded_image', filename=album.album_logo) }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{{ url_for('main.detail', album_id=album.id) }}">View All</a></li>
                <li role="presentation" class="active"><a href="{{ url_for('main.add_song', album_id=album.id) }}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <div class="sub">
                    {{ wtf.quick_form(form) }}
                    </div>
                            <!--<div class="col-sm-offset-2 col-sm-10">-->
                                <!--<button type="submit" class="btn btn-success">Submit</button>-->
                            <!--</div>-->
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

app/templates/main/albums.html
<div class="albums-container">
<div class="col-sm-4 col-lg-2 albums-container">
     <div class="thumbnail">
         <a href="{{ url_for('main.detail', album_id=album.id) }}">
             <img src="{{ album.logo_url }}" class="img-responsive">
         </a>
         <div class="caption">
             <h2>{{ album.album_title }}</h2>
             <h4>{{ album.artist }}</h4>

             <!-- View Details -->
             <a href="{{ url_for('main.detail', album_id=album.id) }}" class="btn btn-primary btn-sm" role="button">View Details</a>

             <!-- Delete Album -->
             <form action="{{ url_for('main.delete_album', album_id=album.id) }}" method="post" style="display: inline;">
                 <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                 <input type="hidden" name="album_id" value="{{ album.id }}" />
                 <button type="submit" class="btn btn-default btn-sm">
                     <span class="glyphicon glyphicon-trash"></span>
                 </button>
             </form>

             <!-- Favorite Album -->
             <button class="btn btn-default btn-sm btn-favorite" role="button" href="{{ url_for('main.favorite_album', album_id=album.id) }}">
                 <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
             </button>
         </div>
     </div>
 </div>
</div>

app/templates/main/details.html
{% extends 'base.html' %}
{% block title %}playsloth - {{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block page_content %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{{ url_for('main.detail', album_id=album.id) }}">
                        {% if album.logo_url %}
                            <img src="{{ album.logo_url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{{ url_for('main.detail', album_id=album.id) }}">View All</a></li>
                <li role="presentation"><a href="{{ url_for('main.add_song', album_id=album.id) }}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in songs %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <audio controls preload="auto" autoplay="false">
                                            <source src="{{ song.audio_url }}" type="audio/mpeg">
                                            Your browser does not support audion in this format
                                        </audio>
                                </td>
                                <td>
                                    <a class="btn-favorite" href="{{ url_for('main.favorite_song', song_id=song.id) }}"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{{url_for('main.delete_song',album_id=album.id, song_id=song.id)}}" method="post" style="display: inline;">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block albums_active %}active{% endblock %}
{% block title %}playsloth - Home{% endblock %}
{% block page_content %}
<div class="albums-container container-fluid">
    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
        {% if albums.items %}
            {% for album in albums.items %}
                {% include 'main/albums.html' %}
                <div class="{{ loop.cycle('', '', '', '', '', 'clearfix visible-lg') }}"></div>
            {% endfor %}

        {% else %}
            {% if current_user.is_authenticated %}
                <div class="col-sm-12">
                    <br>
                    <a href="{{ url_for('main.add_album') }}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                        </button>
                    </a>
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>
    {% if albums.items %}
        {% import 'main/_helpers.html' as helpers %}
        {{ helpers.paginate(albums, 'main.index') }}
    {% endif %}
    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                             <audio controls autoplay>
                                            <source src="{{ song.audio_url }}" type="audio/ogg">
                                            <source src="{{ song.audio_url }}" type="audio/wav">
                                            <source src="{{ song.audio_url }}" type="audio/mp3">
                                            <source src="{{ song.audio_url }}" type="audio/mp4">
                                            Your browser does not support audion in this format
                                        </audio>
                                        </td>
                                        <td>
                                            <a href="{{ url_for('main.detail', album_id=song.album.id) }}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{{ url_for('main.detail', album_id=song.album.id) }}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{{ url_for('main.favorite_song', song_id=song.album.id) }}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}

app/templates/main/songs.html
{% extends 'base.html' %}
{% block title %}
{% if song_filter=='favorites' %}
playsloth - Favorite Songs
{% else %}
playsloth - All Songs
{% endif %}
{% endblock %}
{% block songs_active %}active{% endblock %}

{% block page_content %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if song_filter=='all' %}class="active"{% endif %}><a href="{{ url_for('main.songs', song_filter='all') }}">View All</a></li>
                <li role="presentation" {% if song_filter=='favorites' %}class="active"{% endif %}><a href="{{ url_for('main.songs',song_filter='favorites') }}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <audio controls autoplay>
                                            <source src="{{ song.audio_url }}" type="audio/ogg">
                                            <source src="{{ song.audio_url }}" type="audio/wav">
                                            <source src="{{ song.audio_url }}" type="audio/mp3">
                                            <source src="{{ song.audio_url }}" type="audio/mp4">
                                            Your browser does not support audion in this format
                                        </audio>
                                    </td>
                                    <td>
                                        <a href="{{ url_for('main.detail', album_id=song.album.id) }}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{{ url_for('main.detail', album_id=song.album.id) }}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{{ url_for('main.favorite_song', song_id=song.id) }}" class="btn-favorite"><span id="favid" class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}